### ISSUE TITLE
Initiate bootstrap service on login 

### ISSUE THREAD

**Issue by talwinder50** [trustbloc/hub-auth#17]

**Comment by DRK3** [comment]
[] Add backing store cmd line option, create stores
[] Add "create profile" endpoint
[] Add "retrieve profile" endpoint
[] Add simple client

**Comment by DRK3** [comment]
Split this issue into 4 smaller ones:
https://github.com/trustbloc/hub-auth/issues/18
https://github.com/trustbloc/hub-auth/issues/19
https://github.com/trustbloc/hub-auth/issues/20
https://github.com/trustbloc/hub-auth/issues/21
