### ISSUE TITLE
prepare bootstrap data

### ISSUE THREAD

**Issue by DRK3** [trustbloc/hub-auth#19]

**Comment by llorllale** [comment]
Note: profile == bootstrap data for the web wallet

**Comment by DRK3** [comment]
Expected data to be stored in bootstrap data (AKA "profile)

- SDS server URL
- User primary vault locations
- Key Server URL
- User Key Store IDs

**Comment by llorllale** [comment]
@DRK3 I didn't expect the SDS server URL nor the Key Server URL to be stored with the user's bootstrap data. That can change over time and is in fact configurable no? For sure both should be returned to the user's wallet (along with the rest), but I don't think it should be saved unless I'm missing something here.

**Comment by DRK3** [comment]
@llorllale 👍  You're right - there's no need to save it to the database. You're also correct about it being configurable and could potentially change over time.
